import { GridColDef } from '@mui/x-data-grid';

export const forReceivingColumn = (): GridColDef[] => [
    {
        field: 'chequeNumber',
        headerName: 'Cheque Number',
        headerAlign: 'right',
        align: 'right',
        flex: 1,
        minWidth: 50,
        renderCell: ({ row }) => row.checkable?.chequeNumber,
    },
    {
        field: 'chequeDate',
        headerName: 'Cheque Date',
        headerAlign: 'right',
        align: 'right',
        flex: 1,
        minWidth: 100,
        renderCell: ({ row }) => row.checkable?.chequeDate,
    },
    {
        field: 'type',
        headerName: 'Type Of Check',
        headerAlign: 'right',
        align: 'right',
        flex: 1,
        minWidth: 100,
        renderCell: ({ row }) => row.checkableType,
    },
    {
        field: 'accountName',
        headerName: 'Bank',
        headerAlign: 'right',
        align: 'right',
        flex: 1,
        minWidth: 100,
        renderCell: ({ row }) => row.checkable?.bank,
    },
    {
        field: 'checkAmount',
        headerName: 'Amount',
        headerAlign: 'right',
        align: 'right',
        flex: 1,
        minWidth: 80,
        renderCell: ({ row }) => row.checkable?.amount,
    },
    {
        field: 'location',
        headerName: 'Location',
        headerAlign: 'right',
        align: 'right',
        flex: 1,
        minWidth: 80,
        renderCell: ({ row }) => row.checkable?.tagLocation?.location,
    },

    {
        field: 'status',
        headerName: 'Status',
        headerAlign: 'right',
        align: 'right',
        flex: 1,
        minWidth: 80,
        renderCell: ({ row }) => row.status || '—',
    },
    {
        field: 'createdAt',
        headerName: 'Date Forwarded',
        headerAlign: 'right',
        align: 'right',
        flex: 1,
        minWidth: 80,
    },
];
export const forReceivedColumn = (): GridColDef[] => [
    {
        field: 'chequeNumber',
        headerName: 'Cheque Number',
        headerAlign: 'right',
        align: 'right',
        flex: 1,
        minWidth: 50,
        renderCell: ({ row }) => row.checkable?.chequeNumber,
    },
    {
        field: 'chequeDate',
        headerName: 'Cheque Date',
        headerAlign: 'right',
        align: 'right',
        flex: 1,
        minWidth: 100,
        renderCell: ({ row }) => row.checkable?.chequeDate,
    },
    {
        field: 'type',
        headerName: 'Type Of Check',
        headerAlign: 'right',
        align: 'right',
        flex: 1,
        minWidth: 100,
        renderCell: ({ row }) => row.checkableType,
    },
    {
        field: 'accountName',
        headerName: 'Bank',
        headerAlign: 'right',
        align: 'right',
        flex: 1,
        minWidth: 100,
        renderCell: ({ row }) => row.checkable?.bank,
    },
    {
        field: 'checkAmount',
        headerName: 'Amount',
        headerAlign: 'right',
        align: 'right',
        flex: 1,
        minWidth: 80,
        renderCell: ({ row }) => row.checkable?.amount,
    },
    {
        field: 'location',
        headerName: 'Location',
        headerAlign: 'right',
        align: 'right',
        flex: 1,
        minWidth: 80,
        renderCell: ({ row }) => row.checkable?.tagLocation?.location,
    },

    {
        field: 'received',
        headerName: 'Status',
        headerAlign: 'right',
        align: 'right',
        flex: 1,
        minWidth: 80,
        renderCell: () => 'Received',
    },
    {
        field: 'createdAt',
        headerName: 'Date Received',
        headerAlign: 'right',
        align: 'right',
        flex: 1,
        minWidth: 80,
    },
];
export const statusReleased = (): GridColDef[] => [
    {
        field: 'chequeNumber',
        headerName: 'Cheque Number',
        headerAlign: 'right',
        align: 'right',
        flex: 1,
        minWidth: 50,
        renderCell: ({ row }) => row.checkable?.chequeNumber,
    },
    {
        field: 'chequeDate',
        headerName: 'Cheque Date',
        headerAlign: 'right',
        align: 'right',
        flex: 1,
        minWidth: 100,
        renderCell: ({ row }) => row.checkable?.chequeDate,
    },
    {
        field: 'type',
        headerName: 'Type Of Check',
        headerAlign: 'right',
        align: 'right',
        flex: 1,
        minWidth: 100,
        renderCell: ({ row }) => row.checkableType,
    },
    {
        field: 'accountName',
        headerName: 'Bank',
        headerAlign: 'right',
        align: 'right',
        flex: 1,
        minWidth: 100,
        renderCell: ({ row }) => row.checkable?.bank,
    },
    {
        field: 'checkAmount',
        headerName: 'Amount',
        headerAlign: 'right',
        align: 'right',
        flex: 1,
        minWidth: 80,
        renderCell: ({ row }) => row.checkable?.amount,
    },
    {
        field: 'location',
        headerName: 'Location',
        headerAlign: 'right',
        align: 'right',
        flex: 1,
        minWidth: 80,
        renderCell: ({ row }) => row.checkable?.tagLocation?.location,
    },

    {
        field: 'received',
        headerName: 'Status',
        headerAlign: 'right',
        align: 'right',
        flex: 1,
        minWidth: 80,
        renderCell: () => 'Released',
    },
    {
        field: 'createdAt',
        headerName: 'Date Forwarded',
        headerAlign: 'right',
        align: 'right',
        flex: 1,
        minWidth: 80,
    },
];
